### ISSUE TITLE
Update FSB to 1.7.1

### ISSUE THREAD

**Issue by h3xstream** [codacy/codacy-find-sec-bugs#7]
There were many important updates to FSB
https://github.com/codacy/codacy-find-sec-bugs/blob/86426c60d1978ea0f93467a72b9d128e9d32da31/build.sbt#L33-L35

Latest cli package:
https://github.com/find-sec-bugs/find-sec-bugs/releases/download/version-1.7.1/findsecbugs-cli-1.7.1.zip

**Comment by rtfpessoa** [comment]
Thanks for the heads up. Will update in #8

**Comment by rtfpessoa** [comment]
Fixed
